/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TokenFactoryInterface extends Interface {
    getFunction(nameOrSignature: "INIT_CODE_HASH" | "acceptOwnership" | "allTokens" | "createToken" | "creationFee" | "feeReceiver" | "getAllTokens" | "getTokensByOwner" | "owner" | "pendingOwner" | "predictTokenAddress" | "renounceOwnership" | "setCreationFee" | "setFeeReceiver" | "symbolExists" | "tokensByOwner" | "totalTokens" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeReceiverUpdated" | "FeeUpdated" | "OwnershipTransferStarted" | "OwnershipTransferred" | "TokenCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'INIT_CODE_HASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'allTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createToken', values: [string, string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'creationFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeReceiver', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokensByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictTokenAddress', values: [string, string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCreationFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFeeReceiver', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbolExists', values: [string]): string;
encodeFunctionData(functionFragment: 'tokensByOwner', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'INIT_CODE_HASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creationFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeReceiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokensByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictTokenAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCreationFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeReceiver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbolExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokensByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace FeeReceiverUpdatedEvent {
      export type InputTuple = [newReceiver: AddressLike];
      export type OutputTuple = [newReceiver: string];
      export interface OutputObject {newReceiver: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeUpdatedEvent {
      export type InputTuple = [newFee: BigNumberish];
      export type OutputTuple = [newFee: bigint];
      export interface OutputObject {newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenCreatedEvent {
      export type InputTuple = [token: AddressLike, name: string, symbol: string, supply: BigNumberish, owner: AddressLike, fee: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [token: string, name: string, symbol: string, supply: bigint, owner: string, fee: bigint, timestamp: bigint];
      export interface OutputObject {token: string, name: string, symbol: string, supply: bigint, owner: string, fee: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TokenFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): TokenFactory;
    waitForDeployment(): Promise<this>;

    interface: TokenFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    INIT_CODE_HASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allTokens: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createToken: TypedContractMethod<
      [name: string, symbol: string, initialSupply: BigNumberish, salt: BytesLike, ],
      [string],
      'payable'
    >
    

    
    creationFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeReceiver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAllTokens: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTokensByOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictTokenAddress: TypedContractMethod<
      [name: string, symbol: string, initialSupply: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setCreationFee: TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeReceiver: TypedContractMethod<
      [_receiver: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbolExists: TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >
    

    
    tokensByOwner: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalTokens: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'INIT_CODE_HASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allTokens'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createToken'): TypedContractMethod<
      [name: string, symbol: string, initialSupply: BigNumberish, salt: BytesLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'creationFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeReceiver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllTokens'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokensByOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictTokenAddress'): TypedContractMethod<
      [name: string, symbol: string, initialSupply: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCreationFee'): TypedContractMethod<
      [_fee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeReceiver'): TypedContractMethod<
      [_receiver: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbolExists'): TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tokensByOwner'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalTokens'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FeeReceiverUpdated'): TypedContractEvent<FeeReceiverUpdatedEvent.InputTuple, FeeReceiverUpdatedEvent.OutputTuple, FeeReceiverUpdatedEvent.OutputObject>;
getEvent(key: 'FeeUpdated'): TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenCreated'): TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;

    filters: {
      
      'FeeReceiverUpdated(address)': TypedContractEvent<FeeReceiverUpdatedEvent.InputTuple, FeeReceiverUpdatedEvent.OutputTuple, FeeReceiverUpdatedEvent.OutputObject>;
      FeeReceiverUpdated: TypedContractEvent<FeeReceiverUpdatedEvent.InputTuple, FeeReceiverUpdatedEvent.OutputTuple, FeeReceiverUpdatedEvent.OutputObject>;
    

      'FeeUpdated(uint256)': TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
      FeeUpdated: TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenCreated(address,string,string,uint256,address,uint256,uint256)': TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
      TokenCreated: TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
    
    };
  }