/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleErc20Sol from './SimpleERC20.sol/index.js';
export * as tokenFactorySol from './TokenFactory.sol/index.js';