// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UniswapV2Library$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UniswapV2Library";
  readonly sourceName: "contracts/libraries/UniswapV2Library.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212209a5e7234eb99228f9becedda03b5109e6acdf72d889a6806e0bb657d7308aba264736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212209a5e7234eb99228f9becedda03b5109e6acdf72d889a6806e0bb657d7308aba264736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/UniswapV2Library.sol";
  readonly buildInfoId: "solc-0_8_20-97417d21d699e36cee274c56c6189428d2e07aeb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UniswapV2Library"]: UniswapV2Library$Type;
    ["contracts/libraries/UniswapV2Library.sol:UniswapV2Library"]: UniswapV2Library$Type;
  }
}