// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UQ112x112$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UQ112x112";
  readonly sourceName: "contracts/libraries/UQ112x112.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122014e5aac3a5805f92432d5457e075cbee4a840799be55c943968f5778e8e3b01a64736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122014e5aac3a5805f92432d5457e075cbee4a840799be55c943968f5778e8e3b01a64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/UQ112x112.sol";
  readonly buildInfoId: "solc-0_8_20-97417d21d699e36cee274c56c6189428d2e07aeb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UQ112x112"]: UQ112x112$Type;
    ["contracts/libraries/UQ112x112.sol:UQ112x112"]: UQ112x112$Type;
  }
}