// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUniswapV2Callee$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUniswapV2Callee";
  readonly sourceName: "contracts/interfaces/IUniswapV2Callee.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"uint256","name":"amount0","type":"uint256"},{"internalType":"uint256","name":"amount1","type":"uint256"},{"internalType":"bytes","name":"data","type":"bytes"}],"name":"uniswapV2Call","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IUniswapV2Callee.sol";
  readonly buildInfoId: "solc-0_8_20-97417d21d699e36cee274c56c6189428d2e07aeb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniswapV2Callee"]: IUniswapV2Callee$Type;
    ["contracts/interfaces/IUniswapV2Callee.sol:IUniswapV2Callee"]: IUniswapV2Callee$Type;
  }
}