/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleErc20Sol from './SimpleERC20.sol/index.js';
export type { simpleErc20Sol };
import type * as tokenFactorySol from './TokenFactory.sol/index.js';
export type { tokenFactorySol };
export * as factories from './factories/index.js';
export type { SimpleERC20 } from './SimpleERC20.sol/SimpleERC20.js';
export { SimpleERC20__factory } from './factories/SimpleERC20.sol/SimpleERC20__factory.js';
export type { TokenFactory } from './TokenFactory.sol/TokenFactory.js';
export { TokenFactory__factory } from './factories/TokenFactory.sol/TokenFactory__factory.js';