// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Math$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Math";
  readonly sourceName: "contracts/libraries/Math.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220cedc849f80f1fe8f7e9e61c85a84d03056a3a69654720604eb0a7ddc408860cd64736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220cedc849f80f1fe8f7e9e61c85a84d03056a3a69654720604eb0a7ddc408860cd64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/Math.sol";
  readonly buildInfoId: "solc-0_8_20-97417d21d699e36cee274c56c6189428d2e07aeb";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Math"]: Math$Type;
    ["contracts/libraries/Math.sol:Math"]: Math$Type;
  }
}